### ISSUE TITLE
setup.py install errors on Python 3.10

### ISSUE THREAD

**Issue by buckrogerss** [jeog/TOSDataBridge#40]
Going to try to fix this manually but just passing it on — on a fresh Windows 10/Python 3.10 install I get the following when running setup.py:

```
C:\Users\-----\Documents\Python\TOSDataBridge\python>python setup.py install
C:\Users\-----\Documents\Python\TOSDataBridge\python\setup.py:23: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.core import setup as _setup
running install
running build
pulling constants from C:\Users\Patrick\Documents\Python\TOSDataBridge\python\..\include\tos_databridge.h
  tos_databridge.h:190: TOSDB_CONN_NONE 0
  tos_databridge.h:191: TOSDB_CONN_ENGINE 1
  tos_databridge.h:192: TOSDB_CONN_ENGINE_TOS 2
  tos_databridge.h:194: TOSDB_INTGR_BIT 0x80
  tos_databridge.h:195: TOSDB_QUAD_BIT 0x40
  tos_databridge.h:196: TOSDB_STRING_BIT 0x20
  tos_databridge.h:197: TOSDB_TOPIC_BITMASK 0xe0
  tos_databridge.h:198: TOSDB_STR_DATA_SZ 40
  tos_databridge.h:199: TOSDB_MAX_STR_SZ 0xff
  tos_databridge.h:200: TOSDB_MAX_NSTRS 1000
  tos_databridge.h:201: TOSDB_DEF_TIMEOUT 2000
  tos_databridge.h:202: TOSDB_DEF_PAUSE 100
  tos_databridge.h:204: TOSDB_MIN_TIMEOUT 1500
  tos_databridge.h:206: TOSDB_BLOCK_ID_SZ 63
  tos_databridge.h:208: TOSDB_MAX_BLOCK_SZ 16777216
  tos_databridge.h:212: TOSDB_ERROR_BAD_INPUT -1
  tos_databridge.h:213: TOSDB_ERROR_BAD_INPUT_BUFFER -2
  tos_databridge.h:214: TOSDB_ERROR_NOT_CONNECTED -3
  tos_databridge.h:215: TOSDB_ERROR_TIMEOUT -4
  tos_databridge.h:216: TOSDB_ERROR_BLOCK_ALREADY_EXISTS -5
  tos_databridge.h:217: TOSDB_ERROR_BLOCK_DOESNT_EXIST -6
  tos_databridge.h:218: TOSDB_ERROR_BLOCK_CREATION -7
  tos_databridge.h:219: TOSDB_ERROR_BLOCK_SIZE -8
  tos_databridge.h:220: TOSDB_ERROR_BAD_TOPIC -9
  tos_databridge.h:221: TOSDB_ERROR_BAD_ITEM -10
  tos_databridge.h:222: TOSDB_ERROR_BAD_SIG -11
  tos_databridge.h:223: TOSDB_ERROR_IPC -12
  tos_databridge.h:224: TOSDB_ERROR_IPC_MSG -13
  tos_databridge.h:225: TOSDB_ERROR_CONCURRENCY -14
  tos_databridge.h:226: TOSDB_ERROR_ENGINE_NO_TOPIC -15
  tos_databridge.h:227: TOSDB_ERROR_ENGINE_NO_ITEM -16
  tos_databridge.h:228: TOSDB_ERROR_SERVICE -17
  tos_databridge.h:229: TOSDB_ERROR_GET_DATA -18
  tos_databridge.h:230: TOSDB_ERROR_GET_STATE -19
  tos_databridge.h:231: TOSDB_ERROR_SET_STATE -20
  tos_databridge.h:232: TOSDB_ERROR_DDE_POST -21
  tos_databridge.h:233: TOSDB_ERROR_DDE_NO_ACK -22
  tos_databridge.h:234: TOSDB_ERROR_SHEM_BUFFER -23
  tos_databridge.h:235: TOSDB_ERROR_UNKNOWN -24
  tos_databridge.h:237: TOSDB_ERROR_DECREMENT_BASE -25
pulling topic enum from C:\Users\Patrick\Documents\Python\TOSDataBridge\python\..\include\tos_databridge.h
  tos_databridge.h:418: topic enum BEGIN
  tos_databridge.h:505: topic enum END
auto-generating C:\Users\Patrick\Documents\Python\TOSDataBridge\python\tosdb\_tosdb.py
  checking C:\Users\Patrick\Documents\Python\TOSDataBridge\python\tosdb\_tosdb.py
    fatal: auto-generated C:\Users\Patrick\Documents\Python\TOSDataBridge\python\tosdb\_tosdb.py could not be imported !
    fatal: cannot import name 'Mapping' from 'collections' (C:\Program Files\Python310\lib\collections\__init__.py)
```

The import Mapping from collections issue looks like a common 3.10 problem but it's not immediately clear to me why _tosdb.py doesn't import. 

As a side note, I obviously haven't played with this yet but it's cool of you to release it. Thanks!

**Comment by buckrogerss** [comment]
following up: install works fine on Python 3.8.10
